CLASS /dmo/cl_sc3_bp_behavior DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
      for behavior of /DMO/CESC3BP.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /DMO/CL_SC3_BP_BEHAVIOR IMPLEMENTATION.
ENDCLASS.
